name: template_checker

services:
  checker:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      DATA_DIR: "/data"
    user: "${UID}:${GID}"
    volumes:
      - ./data/:/data:z
      - ./checker/src/:/src:z
    #stdin_open: true
    command: ["python3", "src/main.py"]